### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by Welsh44** [mw75/reveal.js-twocolumn#1]
Hi 

I'm very interesting in using your plugin as I use RvealJs for my presentations.
I use RevealJs with external markdown for the whole content of my presentation, the HTML file only contents calls to CSS, JS and reveal.

I downloaded your repo and try to put `twocolum.js` as a plugin, with a definition of slide in the markdown file as you indicate it.

The plugin is called as in the generated HTML I can see the link to the `twoloumn.css` file.

But the definition of the columns (with quotes) hasn't changed...

have you got some working example including the revealJs configuration ?

thanks in davance

**Comment by mw75** [comment]
Please create a minimal markdown file with no additional plugins and three blockquotes like the ones in the readme and send the generated HTML fragment and any output from the JS console.  
With this plugin the creation of nested blockquotes get modified and the CSS will display the resulting div's as columns. With pure reveal.js i can not imagine whats going wrong.

**Comment by Welsh44** [comment]
Hi
Thanks for the advice. It made me see that I made a mistake using the plugin.
Thanks
